# Site settings
title: Ayres.io
email: admon@ayres.io
#url: ayresdata.github.io
url: http://www.ayres.io
description: "Soporte y Escalamiento de Plataforma de Datos."
keywords: "data engineering databases relational nosql postgresql mysql mariadb clickhouse rethinkdb cockroachdb"
skills: "Soporte y Escalamiento de Platadorma de Datos."
meta_author: Ayres Data

# Google webmaster tools
google_verify: "UA-86497477-1"

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
#contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: ""

menu:
  portfolio: "Servicios"
  about: "Nosotros"
  contact: "Contacto"

nosotros:
  p1: "El crecimiento de una empresa trae aparejado un mayor volumen de datos. Los tiempos de respuesta, seguridad y la disponibilidad de los servicios comienzan a ser más críticos, su plataforma de datos necesita hoy más que nunca, ser eficiente."
  p2: "Nuestra experiencia en clientes de envergadura, nos han dado las herramientas para asesorarlo en el corazón de la información de su empresa."
  button: "Nosotros"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 43B274  #80B3FF
  primary-rgb: "67,178,116" #"128,179,255"
  secondary: 373737  #FD6E8A
  secondary-dark: 373737 0 #A2122F

# Footer settings
footer:
  copyright: Ayres Data
  location: Buenos Aires
  social: ayresdata
  credits: Ayres Data

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/ayresdata
  - title: github
    url: http://github.com/ayresdata
  - title: linkedin
    url: https://www.linkedin.com/company/ayres-data-team/
    #  - title: facebook
    #url:
    #- title: stack-overflow
    #url: http://stackoverflow.com/questions/tagged/jekyll
    #- title: bitbucket
    #url: http://bitbucket.org/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Av. Congreso y Av. Cabildo
  - line: Buenos Aires, Argentina

# Credits content
credits: 'Your Data Stack, matters.'

# Build settings
markdown: kramdown
permalink: pretty
